train_input_path: /home/viniavskyi/Documents/datasets/BRATS/MICCAI_BraTS_2019_Data_Training
test_input_path: /home/viniavskyi/Documents/datasets/BRATS/MICCAI_BraTS_2019_Data_Validation
preprocessed_path: /home/viniavskyi/Documents/datasets/BRATS/preprocessed

background_threshold: 0.02
validation_size: 0.15
