---
project: brain_tumor_segmentation

log_path: /home/viniavskyi/Documents/university/ai/brain_tumor_segmentation/logs

train:
  path: /home/viniavskyi/Documents/datasets/BRATS/preprocessed/train
  width: &WIDTH 192
  height: &HEIGHT 160
  crop: random

val:
  path: /home/viniavskyi/Documents/datasets/BRATS/preprocessed/val
  width: *WIDTH
  height: *HEIGHT
  crop: center

loss:
  name: generalized_dice
  smooth: 1e-5

metrics:
  - dice

num_epochs: 100
batch_size: 12
optimizer:
  name: adam
  lr: 0.0003

scheduler:
  name: plateau
  mode: min
  patience: 5
  factor: 0.5
  min_lr: 0.0000001
